# Generated by Django 3.1.4 on 2021-01-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modeloMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('NombreCliente', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
            ],
        ),
    ]
